

[package]
edition = "2021"
name = "sp-core"
version = "23.0.0"

[lib]
bench = false

[dependencies]
data-encoding = "2.4.0"

[dependencies.array-bytes]
version = "6.1"
optional = true

[dependencies.arrayvec]
version = "0.7.2"
default-features = false

[dependencies.bitflags]
version = "1.3"

[dependencies.blake2]
version = "0.10.4"
optional = true
default-features = false

[dependencies.bounded-collections]
version = "0.1.8"
default-features = false

[dependencies.bs58]
version = "0.5.0"
optional = true
default-features = false

[dependencies.codec]
version = "3.6.1"
features = ["derive", "max-encoded-len"]
default-features = false
package = "parity-scale-codec"

[dependencies.dyn-clonable]
version = "0.9.0"
optional = true

[dependencies.ed25519-zebra]
version = "3.1.0"
optional = true
default-features = false

[dependencies.futures]
version = "0.3.21"
optional = true

[dependencies.hash-db]
version = "0.16.0"
default-features = false

[dependencies.hash256-std-hasher]
version = "0.15.2"
default-features = false

[dependencies.impl-serde]
version = "0.4.0"
optional = true
default-features = false

[dependencies.lazy_static]
version = "1.4.0"
optional = true
default-features = false

[dependencies.libsecp256k1]
version = "0.7"
features = ["static-context"]
optional = true
default-features = false

[dependencies.log]
version = "0.4.17"
default-features = false

[dependencies.merlin]
version = "2.0"
default-features = false

[dependencies.parking_lot]
version = "0.12.1"
optional = true

[dependencies.paste]
version = "1.0.7"

[dependencies.primitive-types]
version = "0.12.0"
features = ["codec", "scale-info"]
default-features = false

[dependencies.rand]
version = "0.8.5"
features = ["small_rng"]
optional = true

[dependencies.regex]
version = "1.6.0"
optional = true

[dependencies.scale-info]
version = "2.5.0"
features = ["derive"]
default-features = false

[dependencies.schnorrkel]
version = "0.9.1"
features = ["preaudit_deprecated", "u64_backend"]
default-features = false

[dependencies.secp256k1]
version = "0.24.0"
features = ["recovery", "alloc"]
optional = true
default-features = false

[dependencies.secrecy]
version = "0.8.0"
default-features = false

[dependencies.serde]
version = "1.0.188"
features = ["derive", "alloc"]
optional = true
default-features = false

[dependencies.sp-core-hashing]
version = "11.0.0"
optional = true
default-features = false

[dependencies.sp-debug-derive]
version = "10.0.0"
default-features = false

[dependencies.sp-externalities]
version = "0.21.0"
optional = true

[dependencies.sp-runtime-interface]
version = "19.0.0"
default-features = false

[dependencies.sp-std]
version = "10.0.0"
default-features = false

[dependencies.sp-storage]
version = "15.0.0"
default-features = false

[dependencies.ss58-registry]
version = "1.34.0"
default-features = false

[dependencies.substrate-bip39]
version = "0.4.4"
optional = true

[dependencies.thiserror]
version = "*"
optional = true

[dependencies.tiny-bip39]
version = "1.0.0"
optional = true

[dependencies.tracing]
version = "0.1.29"
optional = true

[dependencies.w3f-bls]
version = "0.1.3"
optional = true
default-features = false

[dependencies.zeroize]
version = "1.4.3"
default-features = false

[dev-dependencies.criterion]
version = "0.4.0"

[dev-dependencies.serde_json]
version = "1.0"

[features]
bls-experimental = ["w3f-bls"]
default = ["std"]
full_crypto = [
    "array-bytes",
    "blake2",
    "ed25519-zebra",
    "libsecp256k1",
    "secp256k1",
    "sp-core-hashing",
    "sp-runtime-interface/disable_target_static_assertions",
]
serde = [
    "array-bytes",
    "blake2",
    "bounded-collections/serde",
    "bs58/alloc",
    "dep:serde",
    "impl-serde",
    "primitive-types/serde_no_std",
    "scale-info/serde",
    "secrecy/alloc",
    "sp-core-hashing",
    "sp-storage/serde",
]
std = [
    "array-bytes",
    "arrayvec/std",
    "blake2/std",
    "bounded-collections/std",
    "bs58/std",
    "codec/std",
    "dyn-clonable",
    "ed25519-zebra/std",
    "full_crypto",
    "futures",
    "futures/thread-pool",
    "hash-db/std",
    "hash256-std-hasher/std",
    "impl-serde/std",
    "lazy_static",
    "libsecp256k1/std",
    "log/std",
    "merlin/std",
    "parking_lot",
    "primitive-types/byteorder",
    "primitive-types/rustc-hex",
    "primitive-types/serde",
    "primitive-types/std",
    "rand",
    "regex",
    "scale-info/std",
    "schnorrkel/std",
    "secp256k1/global-context",
    "secp256k1/std",
    "secrecy/alloc",
    "serde/std",
    "sp-core-hashing/std",
    "sp-debug-derive/std",
    "sp-externalities/std",
    # "sp-runtime-interface/std",
    "sp-std/std",
    "sp-storage/std",
    "ss58-registry/std",
    "substrate-bip39",
    "thiserror",
    "tiny-bip39",
    "tracing",
    "zeroize/alloc",
]
